name: Build and Release ISO

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged

    steps:
      - name: Checkout repository using git
        run: |
          pacman -Sy git sudo archiso --noconfirm
          git clone --recurse-submodules https://github.com/zstg/StratOS-iso
      
      - name: Build ISO
        id: build_iso
        run: |
          cd StratOS-iso
          export BUILD_DATE=$(date --date="@${SOURCE_DATE_EPOCH:-$(date +%s)}" +%Y.%m.%d)
          sudo bash ./build.sh
          echo "::set-output name=date::${BUILD_DATE}"
      
      - name: Upload ISO to GitHub Release
        uses: xresloader/upload-to-github-release@v1
        with:
          file: 'StratOS-iso/output/StratOS-${BUILD_DATE}.iso'
          tags: true
          draft: false
          overwrite: false
