name: Release ISO

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup distrobox
        run: |
          sudo apt update
          sudo apt install -y git podman 
          curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sudo sh
          git clone --recurse-submodules https://github.com/zstg/StratOS-iso
          distrobox create -i archlinux -n isobuilder -Y

      - name: Build ISO
        id: build_iso
        run: |
          cd StratOS-iso
          export BUILD_DATE=$(distrobox enter -n isobuilder -- date --date="@${SOURCE_DATE_EPOCH:-$(date +%s)}" +%Y.%m.%d)
          #distrobox enter -n isobuilder -- mount -t proc proc /proc
          #distrobox enter -n isobuilder -- mount -t sysfs sys /sys
          #distrobox enter -n isobuilder -- mount --rbind /dev /dev
          #distrobox enter -n isobuilder -- mount --rbind /run /run
          #chmod +x ./build.sh
          distrobox exec -n isobuilder -- sudo bash ./build.sh
          echo "::set-output name=date::${BUILD_DATE}"

      - name: Upload 
        uses: ncipollo/release-action@v1
        with:
          artifacts: "output/*.iso"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.build_iso.outputs.date }}
