name: Release ISO

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup archiso
        run: |
          sudo apt update
          sudo apt install -y git # podman
          sudo apt install -y arch-install-scripts bash dosfstools e2fsprogs erofs-utils grub-common grub-efi-amd64-bin libarchive-dev libisoburn-dev mtools squashfs-tools
          git clone https://github.com/archlinux/archiso 
          cd archiso
          make
          sudo make install-scripts
          sudo make install-profiles
          # curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sudo sh
          # git clone --recurse-submodules https://github.com/zstg/StratOS-iso
          # distrobox create -i archlinux -n isobuilder -Y


      - name: Build ISO
        id: build_iso
        run: |
          git clone --recurse https://github.com/zstg/StratOS-iso
          cd StratOS-iso
          export BUILD_DATE=$(date --date="@${SOURCE_DATE_EPOCH:-$(date +%s)}" +%Y.%m.%d)
          #sudo mount -t proc proc /proc
          #sudo mount -t sysfs sys /sys
          #sudo mount --rbind /dev /dev
          #sudo mount --rbind /run /run
          # sudo pacman -Syy archiso base-devel --noconfirm
          sudo bash ./build.sh
          echo "::set-output name=date::${BUILD_DATE}"

      - name: Upload 
        uses: ncipollo/release-action@v1
        with:
          artifacts: "output/*.iso"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.build_iso.outputs.date }}
