name: Release ISO

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://archlinux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up mkarchiso
        run: | 
          pacman -Sy archiso --noconfirm

      - name: Build ISO
        id: build_iso
        run: |
          ISO_NAME=$(./build.sh)
          echo "::set-output name=iso_name::$ISO_NAME"

      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v2
        with:
          name: StratOS-iso
          path: output/StratOS-*.iso

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: ${{ steps.build_iso.outputs.iso_name }}
          body: |
            Release of the ISO.
          draft: false
          prerelease: false
